exclude: ^workdirs/
repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--config", "setup.cfg"]
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        args: ["--in-place", "--wrap-descriptions", "119", "--wrap-summaries", "119"]
